package com.mcwpaths.kikoz.init;

import com.mcwpaths.kikoz.MacawsPaths;
import com.mcwpaths.kikoz.util.EngravedBlockTooltip;
import com.mcwpaths.kikoz.util.FlattenedBlockTooltip;
import com.mcwpaths.kikoz.util.FuelItemBlock;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;


public class ItemInit {


	public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(MacawsPaths.MOD_ID);

	public static ResourceKey<Item> getKeyForItem(String path) {
		return ResourceKey.create(Registries.ITEM, ResourceLocation.fromNamespaceAndPath(MacawsPaths.MOD_ID, path));
	}



	public static final DeferredItem<Item> OAK_PLANKS_PATH = ITEMS.register("oak_planks_path", () -> new FuelItemBlock(BlockInit.OAK_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("oak_planks_path"))));
	public static final DeferredItem<Item> BIRCH_PLANKS_PATH = ITEMS.register("birch_planks_path", () -> new FuelItemBlock(BlockInit.BIRCH_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("birch_planks_path"))));
	public static final DeferredItem<Item> SPRUCE_PLANKS_PATH = ITEMS.register("spruce_planks_path", () -> new FuelItemBlock(BlockInit.SPRUCE_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("spruce_planks_path"))));
	public static final DeferredItem<Item> JUNGLE_PLANKS_PATH = ITEMS.register("jungle_planks_path", () -> new FuelItemBlock(BlockInit.JUNGLE_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("jungle_planks_path"))));
	public static final DeferredItem<Item> ACACIA_PLANKS_PATH = ITEMS.register("acacia_planks_path", () -> new FuelItemBlock(BlockInit.ACACIA_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("acacia_planks_path"))));
	public static final DeferredItem<Item> DARK_OAK_PLANKS_PATH = ITEMS.register("dark_oak_planks_path", () -> new FuelItemBlock(BlockInit.DARK_OAK_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("dark_oak_planks_path"))));
	public static final DeferredItem<Item> CRIMSON_PLANKS_PATH = ITEMS.register("crimson_planks_path", () -> new FuelItemBlock(BlockInit.CRIMSON_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("crimson_planks_path"))));
	public static final DeferredItem<Item> WARPED_PLANKS_PATH = ITEMS.register("warped_planks_path", () -> new FuelItemBlock(BlockInit.WARPED_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("warped_planks_path"))));
	public static final DeferredItem<Item> MANGROVE_PLANKS_PATH = ITEMS.register("mangrove_planks_path", () -> new FuelItemBlock(BlockInit.MANGROVE_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("mangrove_planks_path"))));


	public static final DeferredItem<Item> ANDESITE_DIAMOND_PAVING = ITEMS.register("andesite_diamond_paving", () -> new BlockItem(BlockInit.ANDESITE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("andesite_diamond_paving"))));
	public static final DeferredItem<Item> ANDESITE_BASKET_WEAVE_PAVING = ITEMS.register("andesite_basket_weave_paving", () -> new BlockItem(BlockInit.ANDESITE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("andesite_basket_weave_paving"))));
	public static final DeferredItem<Item> ANDESITE_SQUARE_PAVING = ITEMS.register("andesite_square_paving", () -> new BlockItem(BlockInit.ANDESITE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("andesite_square_paving"))));
	public static final DeferredItem<Item> ANDESITE_HONEYCOMB_PAVING = ITEMS.register("andesite_honeycomb_paving", () -> new BlockItem(BlockInit.ANDESITE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("andesite_honeycomb_paving"))));
	public static final DeferredItem<Item> ANDESITE_CLOVER_PAVING = ITEMS.register("andesite_clover_paving", () -> new BlockItem(BlockInit.ANDESITE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("andesite_clover_paving"))));
	public static final DeferredItem<Item> ANDESITE_DUMBLE_PAVING = ITEMS.register("andesite_dumble_paving", () -> new BlockItem(BlockInit.ANDESITE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("andesite_dumble_paving"))));

	public static final DeferredItem<Item> DIORITE_DIAMOND_PAVING = ITEMS.register("diorite_diamond_paving", () -> new BlockItem(BlockInit.DIORITE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("diorite_diamond_paving"))));
	public static final DeferredItem<Item> DIORITE_BASKET_WEAVE_PAVING = ITEMS.register("diorite_basket_weave_paving", () -> new BlockItem(BlockInit.DIORITE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("diorite_basket_weave_paving"))));
	public static final DeferredItem<Item> DIORITE_SQUARE_PAVING = ITEMS.register("diorite_square_paving", () -> new BlockItem(BlockInit.DIORITE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("diorite_square_paving"))));
	public static final DeferredItem<Item> DIORITE_HONEYCOMB_PAVING = ITEMS.register("diorite_honeycomb_paving", () -> new BlockItem(BlockInit.DIORITE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("diorite_honeycomb_paving"))));
	public static final DeferredItem<Item> DIORITE_CLOVER_PAVING = ITEMS.register("diorite_clover_paving", () -> new BlockItem(BlockInit.DIORITE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("diorite_clover_paving"))));
	public static final DeferredItem<Item> DIORITE_DUMBLE_PAVING = ITEMS.register("diorite_dumble_paving", () -> new BlockItem(BlockInit.DIORITE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("diorite_dumble_paving"))));

	public static final DeferredItem<Item> GRANITE_DIAMOND_PAVING = ITEMS.register("granite_diamond_paving", () -> new BlockItem(BlockInit.GRANITE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("granite_diamond_paving"))));
	public static final DeferredItem<Item> GRANITE_BASKET_WEAVE_PAVING = ITEMS.register("granite_basket_weave_paving", () -> new BlockItem(BlockInit.GRANITE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("granite_basket_weave_paving"))));
	public static final DeferredItem<Item> GRANITE_SQUARE_PAVING = ITEMS.register("granite_square_paving", () -> new BlockItem(BlockInit.GRANITE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("granite_square_paving"))));
	public static final DeferredItem<Item> GRANITE_HONEYCOMB_PAVING = ITEMS.register("granite_honeycomb_paving", () -> new BlockItem(BlockInit.GRANITE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("granite_honeycomb_paving"))));
	public static final DeferredItem<Item> GRANITE_CLOVER_PAVING = ITEMS.register("granite_clover_paving", () -> new BlockItem(BlockInit.GRANITE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("granite_clover_paving"))));
	public static final DeferredItem<Item> GRANITE_DUMBLE_PAVING = ITEMS.register("granite_dumble_paving", () -> new BlockItem(BlockInit.GRANITE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("granite_dumble_paving"))));

	public static final DeferredItem<Item> SANDSTONE_DIAMOND_PAVING = ITEMS.register("sandstone_diamond_paving", () -> new BlockItem(BlockInit.SANDSTONE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("sandstone_diamond_paving"))));
	public static final DeferredItem<Item> SANDSTONE_BASKET_WEAVE_PAVING = ITEMS.register("sandstone_basket_weave_paving", () -> new BlockItem(BlockInit.SANDSTONE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("sandstone_basket_weave_paving"))));
	public static final DeferredItem<Item> SANDSTONE_SQUARE_PAVING = ITEMS.register("sandstone_square_paving", () -> new BlockItem(BlockInit.SANDSTONE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("sandstone_square_paving"))));
	public static final DeferredItem<Item> SANDSTONE_HONEYCOMB_PAVING = ITEMS.register("sandstone_honeycomb_paving", () -> new BlockItem(BlockInit.SANDSTONE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("sandstone_honeycomb_paving"))));
	public static final DeferredItem<Item> SANDSTONE_CLOVER_PAVING = ITEMS.register("sandstone_clover_paving", () -> new BlockItem(BlockInit.SANDSTONE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("sandstone_clover_paving"))));
	public static final DeferredItem<Item> SANDSTONE_DUMBLE_PAVING = ITEMS.register("sandstone_dumble_paving", () -> new BlockItem(BlockInit.SANDSTONE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("sandstone_dumble_paving"))));

	public static final DeferredItem<Item> RED_SANDSTONE_DIAMOND_PAVING = ITEMS.register("red_sandstone_diamond_paving", () -> new BlockItem(BlockInit.RED_SANDSTONE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_diamond_paving"))));
	public static final DeferredItem<Item> RED_SANDSTONE_BASKET_WEAVE_PAVING = ITEMS.register("red_sandstone_basket_weave_paving", () -> new BlockItem(BlockInit.RED_SANDSTONE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_basket_weave_paving"))));
	public static final DeferredItem<Item> RED_SANDSTONE_SQUARE_PAVING = ITEMS.register("red_sandstone_square_paving", () -> new BlockItem(BlockInit.RED_SANDSTONE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_square_paving"))));
	public static final DeferredItem<Item> RED_SANDSTONE_HONEYCOMB_PAVING = ITEMS.register("red_sandstone_honeycomb_paving", () -> new BlockItem(BlockInit.RED_SANDSTONE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_honeycomb_paving"))));
	public static final DeferredItem<Item> RED_SANDSTONE_CLOVER_PAVING = ITEMS.register("red_sandstone_clover_paving", () -> new BlockItem(BlockInit.RED_SANDSTONE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_clover_paving"))));
	public static final DeferredItem<Item> RED_SANDSTONE_DUMBLE_PAVING = ITEMS.register("red_sandstone_dumble_paving", () -> new BlockItem(BlockInit.RED_SANDSTONE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_dumble_paving"))));

	public static final DeferredItem<Item> BRICK_DIAMOND_PAVING = ITEMS.register("brick_diamond_paving", () -> new BlockItem(BlockInit.BRICK_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("brick_diamond_paving"))));
	public static final DeferredItem<Item> BRICK_BASKET_WEAVE_PAVING = ITEMS.register("brick_basket_weave_paving", () -> new BlockItem(BlockInit.BRICK_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("brick_basket_weave_paving"))));
	public static final DeferredItem<Item> BRICK_SQUARE_PAVING = ITEMS.register("brick_square_paving", () -> new BlockItem(BlockInit.BRICK_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("brick_square_paving"))));
	public static final DeferredItem<Item> BRICK_HONEYCOMB_PAVING = ITEMS.register("brick_honeycomb_paving", () -> new BlockItem(BlockInit.BRICK_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("brick_honeycomb_paving"))));
	public static final DeferredItem<Item> BRICK_CLOVER_PAVING = ITEMS.register("brick_clover_paving", () -> new BlockItem(BlockInit.BRICK_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("brick_clover_paving"))));
	public static final DeferredItem<Item> BRICK_DUMBLE_PAVING = ITEMS.register("brick_dumble_paving", () -> new BlockItem(BlockInit.BRICK_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("brick_dumble_paving"))));

	public static final DeferredItem<Item> COBBLESTONE_DIAMOND_PAVING = ITEMS.register("cobblestone_diamond_paving", () -> new BlockItem(BlockInit.COBBLESTONE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobblestone_diamond_paving"))));
	public static final DeferredItem<Item> COBBLESTONE_BASKET_WEAVE_PAVING = ITEMS.register("cobblestone_basket_weave_paving", () -> new BlockItem(BlockInit.COBBLESTONE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobblestone_basket_weave_paving"))));
	public static final DeferredItem<Item> COBBLESTONE_SQUARE_PAVING = ITEMS.register("cobblestone_square_paving", () -> new BlockItem(BlockInit.COBBLESTONE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobblestone_square_paving"))));
	public static final DeferredItem<Item> COBBLESTONE_HONEYCOMB_PAVING = ITEMS.register("cobblestone_honeycomb_paving", () -> new BlockItem(BlockInit.COBBLESTONE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobblestone_honeycomb_paving"))));
	public static final DeferredItem<Item> COBBLESTONE_CLOVER_PAVING = ITEMS.register("cobblestone_clover_paving", () -> new BlockItem(BlockInit.COBBLESTONE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobblestone_clover_paving"))));
	public static final DeferredItem<Item> COBBLESTONE_DUMBLE_PAVING = ITEMS.register("cobblestone_dumble_paving", () -> new BlockItem(BlockInit.COBBLESTONE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobblestone_dumble_paving"))));

	public static final DeferredItem<Item> MOSSY_COBBLESTONE_DIAMOND_PAVING = ITEMS.register("mossy_cobblestone_diamond_paving", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("mossy_cobblestone_diamond_paving"))));
	public static final DeferredItem<Item> MOSSY_COBBLESTONE_BASKET_WEAVE_PAVING = ITEMS.register("mossy_cobblestone_basket_weave_paving", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("mossy_cobblestone_basket_weave_paving"))));
	public static final DeferredItem<Item> MOSSY_COBBLESTONE_SQUARE_PAVING = ITEMS.register("mossy_cobblestone_square_paving", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("mossy_cobblestone_square_paving"))));
	public static final DeferredItem<Item> MOSSY_COBBLESTONE_HONEYCOMB_PAVING = ITEMS.register("mossy_cobblestone_honeycomb_paving", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("mossy_cobblestone_honeycomb_paving"))));
	public static final DeferredItem<Item> MOSSY_COBBLESTONE_CLOVER_PAVING = ITEMS.register("mossy_cobblestone_clover_paving", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("mossy_cobblestone_clover_paving"))));
	public static final DeferredItem<Item> MOSSY_COBBLESTONE_DUMBLE_PAVING = ITEMS.register("mossy_cobblestone_dumble_paving", () -> new BlockItem(BlockInit.MOSSY_COBBLESTONE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("mossy_cobblestone_dumble_paving"))));

	public static final DeferredItem<Item> COBBLED_DEEPSLATE_DIAMOND_PAVING = ITEMS.register("cobbled_deepslate_diamond_paving", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_diamond_paving"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_BASKET_WEAVE_PAVING = ITEMS.register("cobbled_deepslate_basket_weave_paving", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_basket_weave_paving"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_SQUARE_PAVING = ITEMS.register("cobbled_deepslate_square_paving", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_square_paving"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_HONEYCOMB_PAVING = ITEMS.register("cobbled_deepslate_honeycomb_paving", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_honeycomb_paving"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_CLOVER_PAVING = ITEMS.register("cobbled_deepslate_clover_paving", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_clover_paving"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_DUMBLE_PAVING = ITEMS.register("cobbled_deepslate_dumble_paving", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_dumble_paving"))));

	public static final DeferredItem<Item> DEEPSLATE_DIAMOND_PAVING = ITEMS.register("deepslate_diamond_paving", () -> new BlockItem(BlockInit.DEEPSLATE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("deepslate_diamond_paving"))));
	public static final DeferredItem<Item> DEEPSLATE_BASKET_WEAVE_PAVING = ITEMS.register("deepslate_basket_weave_paving", () -> new BlockItem(BlockInit.DEEPSLATE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("deepslate_basket_weave_paving"))));
	public static final DeferredItem<Item> DEEPSLATE_SQUARE_PAVING = ITEMS.register("deepslate_square_paving", () -> new BlockItem(BlockInit.DEEPSLATE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("deepslate_square_paving"))));
	public static final DeferredItem<Item> DEEPSLATE_HONEYCOMB_PAVING = ITEMS.register("deepslate_honeycomb_paving", () -> new BlockItem(BlockInit.DEEPSLATE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("deepslate_honeycomb_paving"))));
	public static final DeferredItem<Item> DEEPSLATE_CLOVER_PAVING = ITEMS.register("deepslate_clover_paving", () -> new BlockItem(BlockInit.DEEPSLATE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("deepslate_clover_paving"))));
	public static final DeferredItem<Item> DEEPSLATE_DUMBLE_PAVING = ITEMS.register("deepslate_dumble_paving", () -> new BlockItem(BlockInit.DEEPSLATE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("deepslate_dumble_paving"))));

	public static final DeferredItem<Item> MUD_BRICK_DIAMOND_PAVING = ITEMS.register("mud_brick_diamond_paving", () -> new BlockItem(BlockInit.MUD_BRICK_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("mud_brick_diamond_paving"))));
	public static final DeferredItem<Item> MUD_BRICK_BASKET_WEAVE_PAVING = ITEMS.register("mud_brick_basket_weave_paving", () -> new BlockItem(BlockInit.MUD_BRICK_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("mud_brick_basket_weave_paving"))));
	public static final DeferredItem<Item> MUD_BRICK_SQUARE_PAVING = ITEMS.register("mud_brick_square_paving", () -> new BlockItem(BlockInit.MUD_BRICK_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("mud_brick_square_paving"))));
	public static final DeferredItem<Item> MUD_BRICK_HONEYCOMB_PAVING = ITEMS.register("mud_brick_honeycomb_paving", () -> new BlockItem(BlockInit.MUD_BRICK_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("mud_brick_honeycomb_paving"))));
	public static final DeferredItem<Item> MUD_BRICK_CLOVER_PAVING = ITEMS.register("mud_brick_clover_paving", () -> new BlockItem(BlockInit.MUD_BRICK_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("mud_brick_clover_paving"))));
	public static final DeferredItem<Item> MUD_BRICK_DUMBLE_PAVING = ITEMS.register("mud_brick_dumble_paving", () -> new BlockItem(BlockInit.MUD_BRICK_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("mud_brick_dumble_paving"))));

	//1.0.2 Update

	public static final DeferredItem<Item> BLACKSTONE_DIAMOND_PAVING = ITEMS.register("blackstone_diamond_paving", () -> new BlockItem(BlockInit.BLACKSTONE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("blackstone_diamond_paving"))));
	public static final DeferredItem<Item> BLACKSTONE_BASKET_WEAVE_PAVING = ITEMS.register("blackstone_basket_weave_paving", () -> new BlockItem(BlockInit.BLACKSTONE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("blackstone_basket_weave_paving"))));
	public static final DeferredItem<Item> BLACKSTONE_SQUARE_PAVING = ITEMS.register("blackstone_square_paving", () -> new BlockItem(BlockInit.BLACKSTONE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("blackstone_square_paving"))));
	public static final DeferredItem<Item> BLACKSTONE_HONEYCOMB_PAVING = ITEMS.register("blackstone_honeycomb_paving", () -> new BlockItem(BlockInit.BLACKSTONE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("blackstone_honeycomb_paving"))));
	public static final DeferredItem<Item> BLACKSTONE_CLOVER_PAVING = ITEMS.register("blackstone_clover_paving", () -> new BlockItem(BlockInit.BLACKSTONE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("blackstone_clover_paving"))));
	public static final DeferredItem<Item> BLACKSTONE_DUMBLE_PAVING = ITEMS.register("blackstone_dumble_paving", () -> new BlockItem(BlockInit.BLACKSTONE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("blackstone_dumble_paving"))));

	public static final DeferredItem<Item> DARK_PRISMARINE_DIAMOND_PAVING = ITEMS.register("dark_prismarine_diamond_paving", () -> new BlockItem(BlockInit.DARK_PRISMARINE_DIAMOND_PAVING.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_diamond_paving"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_BASKET_WEAVE_PAVING = ITEMS.register("dark_prismarine_basket_weave_paving", () -> new BlockItem(BlockInit.DARK_PRISMARINE_BASKET_WEAVE_PAVING.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_basket_weave_paving"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_SQUARE_PAVING = ITEMS.register("dark_prismarine_square_paving", () -> new BlockItem(BlockInit.DARK_PRISMARINE_SQUARE_PAVING.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_square_paving"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_HONEYCOMB_PAVING = ITEMS.register("dark_prismarine_honeycomb_paving", () -> new BlockItem(BlockInit.DARK_PRISMARINE_HONEYCOMB_PAVING.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_honeycomb_paving"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_CLOVER_PAVING = ITEMS.register("dark_prismarine_clover_paving", () -> new BlockItem(BlockInit.DARK_PRISMARINE_CLOVER_PAVING.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_clover_paving"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_DUMBLE_PAVING = ITEMS.register("dark_prismarine_dumble_paving", () -> new BlockItem(BlockInit.DARK_PRISMARINE_DUMBLE_PAVING.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_dumble_paving"))));

	//1.0.3 Update

	public static final DeferredItem<Item> ANDESITE_RUNNING_BOND_PATH = ITEMS.register("andesite_running_bond_path", () -> new BlockItem(BlockInit.ANDESITE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("andesite_running_bond_path"))));
	public static final DeferredItem<Item> ANDESITE_RUNNING_BOND_SLAB = ITEMS.register("andesite_running_bond_slab", () -> new BlockItem(BlockInit.ANDESITE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("andesite_running_bond_slab"))));
	public static final DeferredItem<Item> ANDESITE_RUNNING_BOND = ITEMS.register("andesite_running_bond", () -> new EngravedBlockTooltip(BlockInit.ANDESITE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("andesite_running_bond"))));

	public static final DeferredItem<Item> DIORITE_RUNNING_BOND_PATH = ITEMS.register("diorite_running_bond_path", () -> new BlockItem(BlockInit.DIORITE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("diorite_running_bond_path"))));
	public static final DeferredItem<Item> DIORITE_RUNNING_BOND_SLAB = ITEMS.register("diorite_running_bond_slab", () -> new BlockItem(BlockInit.DIORITE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("diorite_running_bond_slab"))));
	public static final DeferredItem<Item> DIORITE_RUNNING_BOND = ITEMS.register("diorite_running_bond", () -> new EngravedBlockTooltip(BlockInit.DIORITE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("diorite_running_bond"))));

	public static final DeferredItem<Item> GRANITE_RUNNING_BOND_PATH = ITEMS.register("granite_running_bond_path", () -> new BlockItem(BlockInit.GRANITE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("granite_running_bond_path"))));
	public static final DeferredItem<Item> GRANITE_RUNNING_BOND_SLAB = ITEMS.register("granite_running_bond_slab", () -> new BlockItem(BlockInit.GRANITE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("granite_running_bond_slab"))));
	public static final DeferredItem<Item> GRANITE_RUNNING_BOND = ITEMS.register("granite_running_bond", () -> new EngravedBlockTooltip(BlockInit.GRANITE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("granite_running_bond"))));

	public static final DeferredItem<Item> SANDSTONE_RUNNING_BOND_PATH = ITEMS.register("sandstone_running_bond_path", () -> new BlockItem(BlockInit.SANDSTONE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("sandstone_running_bond_path"))));
	public static final DeferredItem<Item> SANDSTONE_RUNNING_BOND_SLAB = ITEMS.register("sandstone_running_bond_slab", () -> new BlockItem(BlockInit.SANDSTONE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("sandstone_running_bond_slab"))));
	public static final DeferredItem<Item> SANDSTONE_RUNNING_BOND = ITEMS.register("sandstone_running_bond", () -> new EngravedBlockTooltip(BlockInit.SANDSTONE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("sandstone_running_bond"))));

	public static final DeferredItem<Item> RED_SANDSTONE_RUNNING_BOND_PATH = ITEMS.register("red_sandstone_running_bond_path", () -> new BlockItem(BlockInit.RED_SANDSTONE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_running_bond_path"))));
	public static final DeferredItem<Item> RED_SANDSTONE_RUNNING_BOND_SLAB = ITEMS.register("red_sandstone_running_bond_slab", () -> new BlockItem(BlockInit.RED_SANDSTONE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_running_bond_slab"))));
	public static final DeferredItem<Item> RED_SANDSTONE_RUNNING_BOND = ITEMS.register("red_sandstone_running_bond", () -> new EngravedBlockTooltip(BlockInit.RED_SANDSTONE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_running_bond"))));

	public static final DeferredItem<Item> BRICK_RUNNING_BOND_PATH = ITEMS.register("brick_running_bond_path", () -> new BlockItem(BlockInit.BRICK_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("brick_running_bond_path"))));
	public static final DeferredItem<Item> BRICK_RUNNING_BOND_SLAB = ITEMS.register("brick_running_bond_slab", () -> new BlockItem(BlockInit.BRICK_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("brick_running_bond_slab"))));
	public static final DeferredItem<Item> BRICK_RUNNING_BOND = ITEMS.register("brick_running_bond", () -> new EngravedBlockTooltip(BlockInit.BRICK_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("brick_running_bond"))));

	public static final DeferredItem<Item> STONE_RUNNING_BOND_PATH = ITEMS.register("stone_running_bond_path", () -> new BlockItem(BlockInit.STONE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("stone_running_bond_path"))));
	public static final DeferredItem<Item> STONE_RUNNING_BOND_SLAB = ITEMS.register("stone_running_bond_slab", () -> new BlockItem(BlockInit.STONE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("stone_running_bond_slab"))));
	public static final DeferredItem<Item> STONE_RUNNING_BOND = ITEMS.register("stone_running_bond", () -> new EngravedBlockTooltip(BlockInit.STONE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("stone_running_bond"))));

	public static final DeferredItem<Item> MOSSY_STONE_RUNNING_BOND_PATH = ITEMS.register("mossy_stone_running_bond_path", () -> new BlockItem(BlockInit.MOSSY_STONE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_running_bond_path"))));
	public static final DeferredItem<Item> MOSSY_STONE_RUNNING_BOND_SLAB = ITEMS.register("mossy_stone_running_bond_slab", () -> new BlockItem(BlockInit.MOSSY_STONE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_running_bond_slab"))));
	public static final DeferredItem<Item> MOSSY_STONE_RUNNING_BOND = ITEMS.register("mossy_stone_running_bond", () -> new EngravedBlockTooltip(BlockInit.MOSSY_STONE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_running_bond"))));

	public static final DeferredItem<Item> COBBLED_DEEPSLATE_RUNNING_BOND_PATH = ITEMS.register("cobbled_deepslate_running_bond_path", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_running_bond_path"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_RUNNING_BOND_SLAB = ITEMS.register("cobbled_deepslate_running_bond_slab", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_running_bond_slab"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_RUNNING_BOND = ITEMS.register("cobbled_deepslate_running_bond", () -> new EngravedBlockTooltip(BlockInit.COBBLED_DEEPSLATE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_running_bond"))));

	public static final DeferredItem<Item> DEEPSLATE_RUNNING_BOND_PATH = ITEMS.register("deepslate_running_bond_path", () -> new BlockItem(BlockInit.DEEPSLATE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("deepslate_running_bond_path"))));
	public static final DeferredItem<Item> DEEPSLATE_RUNNING_BOND_SLAB = ITEMS.register("deepslate_running_bond_slab", () -> new BlockItem(BlockInit.DEEPSLATE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("deepslate_running_bond_slab"))));
	public static final DeferredItem<Item> DEEPSLATE_RUNNING_BOND = ITEMS.register("deepslate_running_bond", () -> new EngravedBlockTooltip(BlockInit.DEEPSLATE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("deepslate_running_bond"))));

	public static final DeferredItem<Item> MUD_BRICK_RUNNING_BOND_PATH = ITEMS.register("mud_brick_running_bond_path", () -> new BlockItem(BlockInit.MUD_BRICK_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("mud_brick_running_bond_path"))));
	public static final DeferredItem<Item> MUD_BRICK_RUNNING_BOND_SLAB = ITEMS.register("mud_brick_running_bond_slab", () -> new BlockItem(BlockInit.MUD_BRICK_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("mud_brick_running_bond_slab"))));
	public static final DeferredItem<Item> MUD_BRICK_RUNNING_BOND = ITEMS.register("mud_brick_running_bond", () -> new EngravedBlockTooltip(BlockInit.MUD_BRICK_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("mud_brick_running_bond"))));

	public static final DeferredItem<Item> BLACKSTONE_RUNNING_BOND_PATH = ITEMS.register("blackstone_running_bond_path", () -> new BlockItem(BlockInit.BLACKSTONE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("blackstone_running_bond_path"))));
	public static final DeferredItem<Item> BLACKSTONE_RUNNING_BOND_SLAB = ITEMS.register("blackstone_running_bond_slab", () -> new BlockItem(BlockInit.BLACKSTONE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("blackstone_running_bond_slab"))));
	public static final DeferredItem<Item> BLACKSTONE_RUNNING_BOND = ITEMS.register("blackstone_running_bond", () -> new EngravedBlockTooltip(BlockInit.BLACKSTONE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("blackstone_running_bond"))));

	public static final DeferredItem<Item> DARK_PRISMARINE_RUNNING_BOND_PATH = ITEMS.register("dark_prismarine_running_bond_path", () -> new BlockItem(BlockInit.DARK_PRISMARINE_RUNNING_BOND_PATH.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_running_bond_path"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_RUNNING_BOND_SLAB = ITEMS.register("dark_prismarine_running_bond_slab", () -> new BlockItem(BlockInit.DARK_PRISMARINE_RUNNING_BOND_SLAB.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_running_bond_slab"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_RUNNING_BOND = ITEMS.register("dark_prismarine_running_bond", () -> new EngravedBlockTooltip(BlockInit.DARK_PRISMARINE_RUNNING_BOND.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_running_bond"))));

	public static final DeferredItem<Item> CHERRY_PLANKS_PATH = ITEMS.register("cherry_planks_path", () -> new FuelItemBlock(BlockInit.CHERRY_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("cherry_planks_path"))));
	public static final DeferredItem<Item> BAMBOO_PLANKS_PATH = ITEMS.register("bamboo_planks_path", () -> new FuelItemBlock(BlockInit.BAMBOO_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("bamboo_planks_path"))));

	//1.0.5

	public static final DeferredItem<Item> ANDESITE_STREWN_ROCKY_PATH = ITEMS.register("andesite_strewn_rocky_path", () -> new BlockItem(BlockInit.ANDESITE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("andesite_strewn_rocky_path"))));
	public static final DeferredItem<Item> DIORITE_STREWN_ROCKY_PATH = ITEMS.register("diorite_strewn_rocky_path", () -> new BlockItem(BlockInit.DIORITE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("diorite_strewn_rocky_path"))));
	public static final DeferredItem<Item> GRANITE_STREWN_ROCKY_PATH = ITEMS.register("granite_strewn_rocky_path", () -> new BlockItem(BlockInit.GRANITE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("granite_strewn_rocky_path"))));
	public static final DeferredItem<Item> SANDSTONE_STREWN_ROCKY_PATH = ITEMS.register("sandstone_strewn_rocky_path", () -> new BlockItem(BlockInit.SANDSTONE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("sandstone_strewn_rocky_path"))));
	public static final DeferredItem<Item> RED_SANDSTONE_STREWN_ROCKY_PATH = ITEMS.register("red_sandstone_strewn_rocky_path", () -> new BlockItem(BlockInit.RED_SANDSTONE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_strewn_rocky_path"))));
	public static final DeferredItem<Item> BRICK_STREWN_ROCKY_PATH = ITEMS.register("brick_strewn_rocky_path", () -> new BlockItem(BlockInit.BRICK_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("brick_strewn_rocky_path"))));
	public static final DeferredItem<Item> STONE_STREWN_ROCKY_PATH = ITEMS.register("stone_strewn_rocky_path", () -> new BlockItem(BlockInit.STONE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("stone_strewn_rocky_path"))));
	public static final DeferredItem<Item> MOSSY_STONE_STREWN_ROCKY_PATH = ITEMS.register("mossy_stone_strewn_rocky_path", () -> new BlockItem(BlockInit.MOSSY_STONE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_strewn_rocky_path"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_STREWN_ROCKY_PATH = ITEMS.register("cobbled_deepslate_strewn_rocky_path", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_strewn_rocky_path"))));
	public static final DeferredItem<Item> DEEPSLATE_STREWN_ROCKY_PATH = ITEMS.register("deepslate_strewn_rocky_path", () -> new BlockItem(BlockInit.DEEPSLATE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("deepslate_strewn_rocky_path"))));
	public static final DeferredItem<Item> MUD_BRICK_STREWN_ROCKY_PATH = ITEMS.register("mud_brick_strewn_rocky_path", () -> new BlockItem(BlockInit.MUD_BRICK_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("mud_brick_strewn_rocky_path"))));
	public static final DeferredItem<Item> BLACKSTONE_STREWN_ROCKY_PATH = ITEMS.register("blackstone_strewn_rocky_path", () -> new BlockItem(BlockInit.BLACKSTONE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("blackstone_strewn_rocky_path"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_STREWN_ROCKY_PATH = ITEMS.register("dark_prismarine_strewn_rocky_path", () -> new BlockItem(BlockInit.DARK_PRISMARINE_STREWN_ROCKY_PATH.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_strewn_rocky_path"))));

	public static final DeferredItem<Item> ANDESITE_WINDMILL_WEAVE_PATH = ITEMS.register("andesite_windmill_weave_path", () -> new BlockItem(BlockInit.ANDESITE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("andesite_windmill_weave_path"))));
	public static final DeferredItem<Item> ANDESITE_WINDMILL_WEAVE_SLAB = ITEMS.register("andesite_windmill_weave_slab", () -> new BlockItem(BlockInit.ANDESITE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("andesite_windmill_weave_slab"))));
	public static final DeferredItem<Item> ANDESITE_WINDMILL_WEAVE = ITEMS.register("andesite_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.ANDESITE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("andesite_windmill_weave"))));
	public static final DeferredItem<Item> DIORITE_WINDMILL_WEAVE_PATH = ITEMS.register("diorite_windmill_weave_path", () -> new BlockItem(BlockInit.DIORITE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("diorite_windmill_weave_path"))));
	public static final DeferredItem<Item> DIORITE_WINDMILL_WEAVE_SLAB = ITEMS.register("diorite_windmill_weave_slab", () -> new BlockItem(BlockInit.DIORITE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("diorite_windmill_weave_slab"))));
	public static final DeferredItem<Item> DIORITE_WINDMILL_WEAVE = ITEMS.register("diorite_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.DIORITE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("diorite_windmill_weave"))));
	public static final DeferredItem<Item> GRANITE_WINDMILL_WEAVE_PATH = ITEMS.register("granite_windmill_weave_path", () -> new BlockItem(BlockInit.GRANITE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("granite_windmill_weave_path"))));
	public static final DeferredItem<Item> GRANITE_WINDMILL_WEAVE_SLAB = ITEMS.register("granite_windmill_weave_slab", () -> new BlockItem(BlockInit.GRANITE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("granite_windmill_weave_slab"))));
	public static final DeferredItem<Item> GRANITE_WINDMILL_WEAVE = ITEMS.register("granite_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.GRANITE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("granite_windmill_weave"))));
	public static final DeferredItem<Item> SANDSTONE_WINDMILL_WEAVE_PATH = ITEMS.register("sandstone_windmill_weave_path", () -> new BlockItem(BlockInit.SANDSTONE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("sandstone_windmill_weave_path"))));
	public static final DeferredItem<Item> SANDSTONE_WINDMILL_WEAVE_SLAB = ITEMS.register("sandstone_windmill_weave_slab", () -> new BlockItem(BlockInit.SANDSTONE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("sandstone_windmill_weave_slab"))));
	public static final DeferredItem<Item> SANDSTONE_WINDMILL_WEAVE = ITEMS.register("sandstone_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.SANDSTONE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("sandstone_windmill_weave"))));
	public static final DeferredItem<Item> RED_SANDSTONE_WINDMILL_WEAVE_PATH = ITEMS.register("red_sandstone_windmill_weave_path", () -> new BlockItem(BlockInit.RED_SANDSTONE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_windmill_weave_path"))));
	public static final DeferredItem<Item> RED_SANDSTONE_WINDMILL_WEAVE_SLAB = ITEMS.register("red_sandstone_windmill_weave_slab", () -> new BlockItem(BlockInit.RED_SANDSTONE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_windmill_weave_slab"))));
	public static final DeferredItem<Item> RED_SANDSTONE_WINDMILL_WEAVE = ITEMS.register("red_sandstone_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.RED_SANDSTONE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_windmill_weave"))));
	public static final DeferredItem<Item> BRICK_WINDMILL_WEAVE_PATH = ITEMS.register("brick_windmill_weave_path", () -> new BlockItem(BlockInit.BRICK_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("brick_windmill_weave_path"))));
	public static final DeferredItem<Item> BRICK_WINDMILL_WEAVE_SLAB = ITEMS.register("brick_windmill_weave_slab", () -> new BlockItem(BlockInit.BRICK_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("brick_windmill_weave_slab"))));
	public static final DeferredItem<Item> BRICK_WINDMILL_WEAVE = ITEMS.register("brick_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.BRICK_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("brick_windmill_weave"))));
	public static final DeferredItem<Item> STONE_WINDMILL_WEAVE_PATH = ITEMS.register("stone_windmill_weave_path", () -> new BlockItem(BlockInit.STONE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("stone_windmill_weave_path"))));
	public static final DeferredItem<Item> STONE_WINDMILL_WEAVE_SLAB = ITEMS.register("stone_windmill_weave_slab", () -> new BlockItem(BlockInit.STONE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("stone_windmill_weave_slab"))));
	public static final DeferredItem<Item> STONE_WINDMILL_WEAVE = ITEMS.register("stone_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.STONE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("stone_windmill_weave"))));
	public static final DeferredItem<Item> MOSSY_STONE_WINDMILL_WEAVE_PATH = ITEMS.register("mossy_stone_windmill_weave_path", () -> new BlockItem(BlockInit.MOSSY_STONE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_windmill_weave_path"))));
	public static final DeferredItem<Item> MOSSY_STONE_WINDMILL_WEAVE_SLAB = ITEMS.register("mossy_stone_windmill_weave_slab", () -> new BlockItem(BlockInit.MOSSY_STONE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_windmill_weave_slab"))));
	public static final DeferredItem<Item> MOSSY_STONE_WINDMILL_WEAVE = ITEMS.register("mossy_stone_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.MOSSY_STONE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_windmill_weave"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_WINDMILL_WEAVE_PATH = ITEMS.register("cobbled_deepslate_windmill_weave_path", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_windmill_weave_path"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_WINDMILL_WEAVE_SLAB = ITEMS.register("cobbled_deepslate_windmill_weave_slab", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_windmill_weave_slab"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_WINDMILL_WEAVE = ITEMS.register("cobbled_deepslate_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.COBBLED_DEEPSLATE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_windmill_weave"))));
	public static final DeferredItem<Item> DEEPSLATE_WINDMILL_WEAVE_PATH = ITEMS.register("deepslate_windmill_weave_path", () -> new BlockItem(BlockInit.DEEPSLATE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("deepslate_windmill_weave_path"))));
	public static final DeferredItem<Item> DEEPSLATE_WINDMILL_WEAVE_SLAB = ITEMS.register("deepslate_windmill_weave_slab", () -> new BlockItem(BlockInit.DEEPSLATE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("deepslate_windmill_weave_slab"))));
	public static final DeferredItem<Item> DEEPSLATE_WINDMILL_WEAVE = ITEMS.register("deepslate_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.DEEPSLATE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("deepslate_windmill_weave"))));
	public static final DeferredItem<Item> MUD_BRICK_WINDMILL_WEAVE_PATH = ITEMS.register("mud_brick_windmill_weave_path", () -> new BlockItem(BlockInit.MUD_BRICK_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("mud_brick_windmill_weave_path"))));
	public static final DeferredItem<Item> MUD_BRICK_WINDMILL_WEAVE_SLAB = ITEMS.register("mud_brick_windmill_weave_slab", () -> new BlockItem(BlockInit.MUD_BRICK_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("mud_brick_windmill_weave_slab"))));
	public static final DeferredItem<Item> MUD_BRICK_WINDMILL_WEAVE = ITEMS.register("mud_brick_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.MUD_BRICK_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("mud_brick_windmill_weave"))));
	public static final DeferredItem<Item> BLACKSTONE_WINDMILL_WEAVE_PATH = ITEMS.register("blackstone_windmill_weave_path", () -> new BlockItem(BlockInit.BLACKSTONE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("blackstone_windmill_weave_path"))));
	public static final DeferredItem<Item> BLACKSTONE_WINDMILL_WEAVE_SLAB = ITEMS.register("blackstone_windmill_weave_slab", () -> new BlockItem(BlockInit.BLACKSTONE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("blackstone_windmill_weave_slab"))));
	public static final DeferredItem<Item> BLACKSTONE_WINDMILL_WEAVE = ITEMS.register("blackstone_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.BLACKSTONE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("blackstone_windmill_weave"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_WINDMILL_WEAVE_PATH = ITEMS.register("dark_prismarine_windmill_weave_path", () -> new BlockItem(BlockInit.DARK_PRISMARINE_WINDMILL_WEAVE_PATH.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_windmill_weave_path"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_WINDMILL_WEAVE_SLAB = ITEMS.register("dark_prismarine_windmill_weave_slab", () -> new BlockItem(BlockInit.DARK_PRISMARINE_WINDMILL_WEAVE_SLAB.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_windmill_weave_slab"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_WINDMILL_WEAVE = ITEMS.register("dark_prismarine_windmill_weave", () -> new EngravedBlockTooltip(BlockInit.DARK_PRISMARINE_WINDMILL_WEAVE.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_windmill_weave"))));

	public static final DeferredItem<Item> ANDESITE_FLAGSTONE_PATH = ITEMS.register("andesite_flagstone_path", () -> new BlockItem(BlockInit.ANDESITE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("andesite_flagstone_path"))));
	public static final DeferredItem<Item> ANDESITE_FLAGSTONE_SLAB = ITEMS.register("andesite_flagstone_slab", () -> new BlockItem(BlockInit.ANDESITE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("andesite_flagstone_slab"))));
	public static final DeferredItem<Item> ANDESITE_FLAGSTONE = ITEMS.register("andesite_flagstone", () -> new EngravedBlockTooltip(BlockInit.ANDESITE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("andesite_flagstone"))));
	public static final DeferredItem<Item> DIORITE_FLAGSTONE_PATH = ITEMS.register("diorite_flagstone_path", () -> new BlockItem(BlockInit.DIORITE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("diorite_flagstone_path"))));
	public static final DeferredItem<Item> DIORITE_FLAGSTONE_SLAB = ITEMS.register("diorite_flagstone_slab", () -> new BlockItem(BlockInit.DIORITE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("diorite_flagstone_slab"))));
	public static final DeferredItem<Item> DIORITE_FLAGSTONE = ITEMS.register("diorite_flagstone", () -> new EngravedBlockTooltip(BlockInit.DIORITE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("diorite_flagstone"))));
	public static final DeferredItem<Item> GRANITE_FLAGSTONE_PATH = ITEMS.register("granite_flagstone_path", () -> new BlockItem(BlockInit.GRANITE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("granite_flagstone_path"))));
	public static final DeferredItem<Item> GRANITE_FLAGSTONE_SLAB = ITEMS.register("granite_flagstone_slab", () -> new BlockItem(BlockInit.GRANITE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("granite_flagstone_slab"))));
	public static final DeferredItem<Item> GRANITE_FLAGSTONE = ITEMS.register("granite_flagstone", () -> new EngravedBlockTooltip(BlockInit.GRANITE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("granite_flagstone"))));
	public static final DeferredItem<Item> SANDSTONE_FLAGSTONE_PATH = ITEMS.register("sandstone_flagstone_path", () -> new BlockItem(BlockInit.SANDSTONE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("sandstone_flagstone_path"))));
	public static final DeferredItem<Item> SANDSTONE_FLAGSTONE_SLAB = ITEMS.register("sandstone_flagstone_slab", () -> new BlockItem(BlockInit.SANDSTONE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("sandstone_flagstone_slab"))));
	public static final DeferredItem<Item> SANDSTONE_FLAGSTONE = ITEMS.register("sandstone_flagstone", () -> new EngravedBlockTooltip(BlockInit.SANDSTONE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("sandstone_flagstone"))));
	public static final DeferredItem<Item> RED_SANDSTONE_FLAGSTONE_PATH = ITEMS.register("red_sandstone_flagstone_path", () -> new BlockItem(BlockInit.RED_SANDSTONE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_flagstone_path"))));
	public static final DeferredItem<Item> RED_SANDSTONE_FLAGSTONE_SLAB = ITEMS.register("red_sandstone_flagstone_slab", () -> new BlockItem(BlockInit.RED_SANDSTONE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_flagstone_slab"))));
	public static final DeferredItem<Item> RED_SANDSTONE_FLAGSTONE = ITEMS.register("red_sandstone_flagstone", () -> new EngravedBlockTooltip(BlockInit.RED_SANDSTONE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_flagstone"))));
	public static final DeferredItem<Item> BRICK_FLAGSTONE_PATH = ITEMS.register("brick_flagstone_path", () -> new BlockItem(BlockInit.BRICK_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("brick_flagstone_path"))));
	public static final DeferredItem<Item> BRICK_FLAGSTONE_SLAB = ITEMS.register("brick_flagstone_slab", () -> new BlockItem(BlockInit.BRICK_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("brick_flagstone_slab"))));
	public static final DeferredItem<Item> BRICK_FLAGSTONE = ITEMS.register("brick_flagstone", () -> new EngravedBlockTooltip(BlockInit.BRICK_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("brick_flagstone"))));
	public static final DeferredItem<Item> STONE_FLAGSTONE_PATH = ITEMS.register("stone_flagstone_path", () -> new BlockItem(BlockInit.STONE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("stone_flagstone_path"))));
	public static final DeferredItem<Item> STONE_FLAGSTONE_SLAB = ITEMS.register("stone_flagstone_slab", () -> new BlockItem(BlockInit.STONE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("stone_flagstone_slab"))));
	public static final DeferredItem<Item> STONE_FLAGSTONE = ITEMS.register("stone_flagstone", () -> new EngravedBlockTooltip(BlockInit.STONE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("stone_flagstone"))));
	public static final DeferredItem<Item> MOSSY_STONE_FLAGSTONE_PATH = ITEMS.register("mossy_stone_flagstone_path", () -> new BlockItem(BlockInit.MOSSY_STONE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_flagstone_path"))));
	public static final DeferredItem<Item> MOSSY_STONE_FLAGSTONE_SLAB = ITEMS.register("mossy_stone_flagstone_slab", () -> new BlockItem(BlockInit.MOSSY_STONE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_flagstone_slab"))));
	public static final DeferredItem<Item> MOSSY_STONE_FLAGSTONE = ITEMS.register("mossy_stone_flagstone", () -> new EngravedBlockTooltip(BlockInit.MOSSY_STONE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_flagstone"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_FLAGSTONE_PATH = ITEMS.register("cobbled_deepslate_flagstone_path", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_flagstone_path"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_FLAGSTONE_SLAB = ITEMS.register("cobbled_deepslate_flagstone_slab", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_flagstone_slab"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_FLAGSTONE = ITEMS.register("cobbled_deepslate_flagstone", () -> new EngravedBlockTooltip(BlockInit.COBBLED_DEEPSLATE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_flagstone"))));
	public static final DeferredItem<Item> DEEPSLATE_FLAGSTONE_PATH = ITEMS.register("deepslate_flagstone_path", () -> new BlockItem(BlockInit.DEEPSLATE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("deepslate_flagstone_path"))));
	public static final DeferredItem<Item> DEEPSLATE_FLAGSTONE_SLAB = ITEMS.register("deepslate_flagstone_slab", () -> new BlockItem(BlockInit.DEEPSLATE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("deepslate_flagstone_slab"))));
	public static final DeferredItem<Item> DEEPSLATE_FLAGSTONE = ITEMS.register("deepslate_flagstone", () -> new EngravedBlockTooltip(BlockInit.DEEPSLATE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("deepslate_flagstone"))));
	public static final DeferredItem<Item> MUD_BRICK_FLAGSTONE_PATH = ITEMS.register("mud_brick_flagstone_path", () -> new BlockItem(BlockInit.MUD_BRICK_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("mud_brick_flagstone_path"))));
	public static final DeferredItem<Item> MUD_BRICK_FLAGSTONE_SLAB = ITEMS.register("mud_brick_flagstone_slab", () -> new BlockItem(BlockInit.MUD_BRICK_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("mud_brick_flagstone_slab"))));
	public static final DeferredItem<Item> MUD_BRICK_FLAGSTONE = ITEMS.register("mud_brick_flagstone", () -> new EngravedBlockTooltip(BlockInit.MUD_BRICK_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("mud_brick_flagstone"))));
	public static final DeferredItem<Item> BLACKSTONE_FLAGSTONE_PATH = ITEMS.register("blackstone_flagstone_path", () -> new BlockItem(BlockInit.BLACKSTONE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("blackstone_flagstone_path"))));
	public static final DeferredItem<Item> BLACKSTONE_FLAGSTONE_SLAB = ITEMS.register("blackstone_flagstone_slab", () -> new BlockItem(BlockInit.BLACKSTONE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("blackstone_flagstone_slab"))));
	public static final DeferredItem<Item> BLACKSTONE_FLAGSTONE = ITEMS.register("blackstone_flagstone", () -> new EngravedBlockTooltip(BlockInit.BLACKSTONE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("blackstone_flagstone"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_FLAGSTONE_PATH = ITEMS.register("dark_prismarine_flagstone_path", () -> new BlockItem(BlockInit.DARK_PRISMARINE_FLAGSTONE_PATH.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_flagstone_path"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_FLAGSTONE_SLAB = ITEMS.register("dark_prismarine_flagstone_slab", () -> new BlockItem(BlockInit.DARK_PRISMARINE_FLAGSTONE_SLAB.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_flagstone_slab"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_FLAGSTONE = ITEMS.register("dark_prismarine_flagstone", () -> new EngravedBlockTooltip(BlockInit.DARK_PRISMARINE_FLAGSTONE.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_flagstone"))));

	public static final DeferredItem<Item> ANDESITE_CRYSTAL_FLOOR_PATH = ITEMS.register("andesite_crystal_floor_path", () -> new BlockItem(BlockInit.ANDESITE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("andesite_crystal_floor_path"))));
	public static final DeferredItem<Item> ANDESITE_CRYSTAL_FLOOR_SLAB = ITEMS.register("andesite_crystal_floor_slab", () -> new BlockItem(BlockInit.ANDESITE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("andesite_crystal_floor_slab"))));
	public static final DeferredItem<Item> ANDESITE_CRYSTAL_FLOOR = ITEMS.register("andesite_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.ANDESITE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("andesite_crystal_floor"))));
	public static final DeferredItem<Item> DIORITE_CRYSTAL_FLOOR_PATH = ITEMS.register("diorite_crystal_floor_path", () -> new BlockItem(BlockInit.DIORITE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("diorite_crystal_floor_path"))));
	public static final DeferredItem<Item> DIORITE_CRYSTAL_FLOOR_SLAB = ITEMS.register("diorite_crystal_floor_slab", () -> new BlockItem(BlockInit.DIORITE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("diorite_crystal_floor_slab"))));
	public static final DeferredItem<Item> DIORITE_CRYSTAL_FLOOR = ITEMS.register("diorite_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.DIORITE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("diorite_crystal_floor"))));
	public static final DeferredItem<Item> GRANITE_CRYSTAL_FLOOR_PATH = ITEMS.register("granite_crystal_floor_path", () -> new BlockItem(BlockInit.GRANITE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("granite_crystal_floor_path"))));
	public static final DeferredItem<Item> GRANITE_CRYSTAL_FLOOR_SLAB = ITEMS.register("granite_crystal_floor_slab", () -> new BlockItem(BlockInit.GRANITE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("granite_crystal_floor_slab"))));
	public static final DeferredItem<Item> GRANITE_CRYSTAL_FLOOR = ITEMS.register("granite_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.GRANITE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("granite_crystal_floor"))));
	public static final DeferredItem<Item> SANDSTONE_CRYSTAL_FLOOR_PATH = ITEMS.register("sandstone_crystal_floor_path", () -> new BlockItem(BlockInit.SANDSTONE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("sandstone_crystal_floor_path"))));
	public static final DeferredItem<Item> SANDSTONE_CRYSTAL_FLOOR_SLAB = ITEMS.register("sandstone_crystal_floor_slab", () -> new BlockItem(BlockInit.SANDSTONE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("sandstone_crystal_floor_slab"))));
	public static final DeferredItem<Item> SANDSTONE_CRYSTAL_FLOOR = ITEMS.register("sandstone_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.SANDSTONE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("sandstone_crystal_floor"))));
	public static final DeferredItem<Item> RED_SANDSTONE_CRYSTAL_FLOOR_PATH = ITEMS.register("red_sandstone_crystal_floor_path", () -> new BlockItem(BlockInit.RED_SANDSTONE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_crystal_floor_path"))));
	public static final DeferredItem<Item> RED_SANDSTONE_CRYSTAL_FLOOR_SLAB = ITEMS.register("red_sandstone_crystal_floor_slab", () -> new BlockItem(BlockInit.RED_SANDSTONE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_crystal_floor_slab"))));
	public static final DeferredItem<Item> RED_SANDSTONE_CRYSTAL_FLOOR = ITEMS.register("red_sandstone_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.RED_SANDSTONE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_crystal_floor"))));
	public static final DeferredItem<Item> BRICK_CRYSTAL_FLOOR_PATH = ITEMS.register("brick_crystal_floor_path", () -> new BlockItem(BlockInit.BRICK_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("brick_crystal_floor_path"))));
	public static final DeferredItem<Item> BRICK_CRYSTAL_FLOOR_SLAB = ITEMS.register("brick_crystal_floor_slab", () -> new BlockItem(BlockInit.BRICK_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("brick_crystal_floor_slab"))));
	public static final DeferredItem<Item> BRICK_CRYSTAL_FLOOR = ITEMS.register("brick_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.BRICK_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("brick_crystal_floor"))));
	public static final DeferredItem<Item> STONE_CRYSTAL_FLOOR_PATH = ITEMS.register("stone_crystal_floor_path", () -> new BlockItem(BlockInit.STONE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("stone_crystal_floor_path"))));
	public static final DeferredItem<Item> STONE_CRYSTAL_FLOOR_SLAB = ITEMS.register("stone_crystal_floor_slab", () -> new BlockItem(BlockInit.STONE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("stone_crystal_floor_slab"))));
	public static final DeferredItem<Item> STONE_CRYSTAL_FLOOR = ITEMS.register("stone_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.STONE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("stone_crystal_floor"))));
	public static final DeferredItem<Item> MOSSY_STONE_CRYSTAL_FLOOR_PATH = ITEMS.register("mossy_stone_crystal_floor_path", () -> new BlockItem(BlockInit.MOSSY_STONE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_crystal_floor_path"))));
	public static final DeferredItem<Item> MOSSY_STONE_CRYSTAL_FLOOR_SLAB = ITEMS.register("mossy_stone_crystal_floor_slab", () -> new BlockItem(BlockInit.MOSSY_STONE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_crystal_floor_slab"))));
	public static final DeferredItem<Item> MOSSY_STONE_CRYSTAL_FLOOR = ITEMS.register("mossy_stone_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.MOSSY_STONE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_crystal_floor"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_CRYSTAL_FLOOR_PATH = ITEMS.register("cobbled_deepslate_crystal_floor_path", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_crystal_floor_path"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_CRYSTAL_FLOOR_SLAB = ITEMS.register("cobbled_deepslate_crystal_floor_slab", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_crystal_floor_slab"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_CRYSTAL_FLOOR = ITEMS.register("cobbled_deepslate_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.COBBLED_DEEPSLATE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_crystal_floor"))));
	public static final DeferredItem<Item> DEEPSLATE_CRYSTAL_FLOOR_PATH = ITEMS.register("deepslate_crystal_floor_path", () -> new BlockItem(BlockInit.DEEPSLATE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("deepslate_crystal_floor_path"))));
	public static final DeferredItem<Item> DEEPSLATE_CRYSTAL_FLOOR_SLAB = ITEMS.register("deepslate_crystal_floor_slab", () -> new BlockItem(BlockInit.DEEPSLATE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("deepslate_crystal_floor_slab"))));
	public static final DeferredItem<Item> DEEPSLATE_CRYSTAL_FLOOR = ITEMS.register("deepslate_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.DEEPSLATE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("deepslate_crystal_floor"))));
	public static final DeferredItem<Item> MUD_BRICK_CRYSTAL_FLOOR_PATH = ITEMS.register("mud_brick_crystal_floor_path", () -> new BlockItem(BlockInit.MUD_BRICK_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("mud_brick_crystal_floor_path"))));
	public static final DeferredItem<Item> MUD_BRICK_CRYSTAL_FLOOR_SLAB = ITEMS.register("mud_brick_crystal_floor_slab", () -> new BlockItem(BlockInit.MUD_BRICK_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("mud_brick_crystal_floor_slab"))));
	public static final DeferredItem<Item> MUD_BRICK_CRYSTAL_FLOOR = ITEMS.register("mud_brick_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.MUD_BRICK_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("mud_brick_crystal_floor"))));
	public static final DeferredItem<Item> BLACKSTONE_CRYSTAL_FLOOR_PATH = ITEMS.register("blackstone_crystal_floor_path", () -> new BlockItem(BlockInit.BLACKSTONE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("blackstone_crystal_floor_path"))));
	public static final DeferredItem<Item> BLACKSTONE_CRYSTAL_FLOOR_SLAB = ITEMS.register("blackstone_crystal_floor_slab", () -> new BlockItem(BlockInit.BLACKSTONE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("blackstone_crystal_floor_slab"))));
	public static final DeferredItem<Item> BLACKSTONE_CRYSTAL_FLOOR = ITEMS.register("blackstone_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.BLACKSTONE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("blackstone_crystal_floor"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_CRYSTAL_FLOOR_PATH = ITEMS.register("dark_prismarine_crystal_floor_path", () -> new BlockItem(BlockInit.DARK_PRISMARINE_CRYSTAL_FLOOR_PATH.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_crystal_floor_path"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_CRYSTAL_FLOOR_SLAB = ITEMS.register("dark_prismarine_crystal_floor_slab", () -> new BlockItem(BlockInit.DARK_PRISMARINE_CRYSTAL_FLOOR_SLAB.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_crystal_floor_slab"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_CRYSTAL_FLOOR = ITEMS.register("dark_prismarine_crystal_floor", () -> new EngravedBlockTooltip(BlockInit.DARK_PRISMARINE_CRYSTAL_FLOOR.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_crystal_floor"))));

	//1.1.0 stuff

	public static final DeferredItem<Item> PODZOL_PATH_BLOCK = ITEMS.register("podzol_path_block", () -> new FlattenedBlockTooltip(BlockInit.PODZOL_PATH_BLOCK.get(), new Item.Properties().setId(getKeyForItem("podzol_path_block"))));
	public static final DeferredItem<Item> DIRT_PATH_BLOCK = ITEMS.register("dirt_path_block", () -> new FlattenedBlockTooltip(BlockInit.DIRT_PATH_BLOCK.get(), new Item.Properties().setId(getKeyForItem("dirt_path_block"))));
	public static final DeferredItem<Item> GRAVEL_PATH_BLOCK = ITEMS.register("gravel_path_block", () -> new FlattenedBlockTooltip(BlockInit.GRAVEL_PATH_BLOCK.get(), new Item.Properties().setId(getKeyForItem("gravel_path_block"))));
	public static final DeferredItem<Item> SAND_PATH_BLOCK = ITEMS.register("sand_path_block", () -> new FlattenedBlockTooltip(BlockInit.SAND_PATH_BLOCK.get(), new Item.Properties().setId(getKeyForItem("sand_path_block"))));
	public static final DeferredItem<Item> RED_SAND_PATH_BLOCK = ITEMS.register("red_sand_path_block", () -> new FlattenedBlockTooltip(BlockInit.RED_SAND_PATH_BLOCK.get(), new Item.Properties().setId(getKeyForItem("red_sand_path_block"))));

	public static final DeferredItem<Item> ANDESITE_RUNNING_BOND_STAIRS = ITEMS.register("andesite_running_bond_stairs", () -> new BlockItem(BlockInit.ANDESITE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("andesite_running_bond_stairs"))));
	public static final DeferredItem<Item> DIORITE_RUNNING_BOND_STAIRS = ITEMS.register("diorite_running_bond_stairs", () -> new BlockItem(BlockInit.DIORITE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("diorite_running_bond_stairs"))));
	public static final DeferredItem<Item> GRANITE_RUNNING_BOND_STAIRS = ITEMS.register("granite_running_bond_stairs", () -> new BlockItem(BlockInit.GRANITE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("granite_running_bond_stairs"))));
	public static final DeferredItem<Item> SANDSTONE_RUNNING_BOND_STAIRS = ITEMS.register("sandstone_running_bond_stairs", () -> new BlockItem(BlockInit.SANDSTONE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("sandstone_running_bond_stairs"))));
	public static final DeferredItem<Item> RED_SANDSTONE_RUNNING_BOND_STAIRS = ITEMS.register("red_sandstone_running_bond_stairs", () -> new BlockItem(BlockInit.RED_SANDSTONE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_running_bond_stairs"))));
	public static final DeferredItem<Item> BRICK_RUNNING_BOND_STAIRS = ITEMS.register("brick_running_bond_stairs", () -> new BlockItem(BlockInit.BRICK_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("brick_running_bond_stairs"))));
	public static final DeferredItem<Item> STONE_RUNNING_BOND_STAIRS = ITEMS.register("stone_running_bond_stairs", () -> new BlockItem(BlockInit.STONE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("stone_running_bond_stairs"))));
	public static final DeferredItem<Item> MOSSY_STONE_RUNNING_BOND_STAIRS = ITEMS.register("mossy_stone_running_bond_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_running_bond_stairs"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_RUNNING_BOND_STAIRS = ITEMS.register("cobbled_deepslate_running_bond_stairs", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_running_bond_stairs"))));
	public static final DeferredItem<Item> DEEPSLATE_RUNNING_BOND_STAIRS = ITEMS.register("deepslate_running_bond_stairs", () -> new BlockItem(BlockInit.DEEPSLATE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("deepslate_running_bond_stairs"))));
	public static final DeferredItem<Item> MUD_BRICK_RUNNING_BOND_STAIRS = ITEMS.register("mud_brick_running_bond_stairs", () -> new BlockItem(BlockInit.MUD_BRICK_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("mud_brick_running_bond_stairs"))));
	public static final DeferredItem<Item> BLACKSTONE_RUNNING_BOND_STAIRS = ITEMS.register("blackstone_running_bond_stairs", () -> new BlockItem(BlockInit.BLACKSTONE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("blackstone_running_bond_stairs"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_RUNNING_BOND_STAIRS = ITEMS.register("dark_prismarine_running_bond_stairs", () -> new BlockItem(BlockInit.DARK_PRISMARINE_RUNNING_BOND_STAIRS.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_running_bond_stairs"))));

	public static final DeferredItem<Item> ANDESITE_WINDMILL_WEAVE_STAIRS = ITEMS.register("andesite_windmill_weave_stairs", () -> new BlockItem(BlockInit.ANDESITE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("andesite_windmill_weave_stairs"))));
	public static final DeferredItem<Item> DIORITE_WINDMILL_WEAVE_STAIRS = ITEMS.register("diorite_windmill_weave_stairs", () -> new BlockItem(BlockInit.DIORITE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("diorite_windmill_weave_stairs"))));
	public static final DeferredItem<Item> GRANITE_WINDMILL_WEAVE_STAIRS = ITEMS.register("granite_windmill_weave_stairs", () -> new BlockItem(BlockInit.GRANITE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("granite_windmill_weave_stairs"))));
	public static final DeferredItem<Item> SANDSTONE_WINDMILL_WEAVE_STAIRS = ITEMS.register("sandstone_windmill_weave_stairs", () -> new BlockItem(BlockInit.SANDSTONE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("sandstone_windmill_weave_stairs"))));
	public static final DeferredItem<Item> RED_SANDSTONE_WINDMILL_WEAVE_STAIRS = ITEMS.register("red_sandstone_windmill_weave_stairs", () -> new BlockItem(BlockInit.RED_SANDSTONE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_windmill_weave_stairs"))));
	public static final DeferredItem<Item> BRICK_WINDMILL_WEAVE_STAIRS = ITEMS.register("brick_windmill_weave_stairs", () -> new BlockItem(BlockInit.BRICK_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("brick_windmill_weave_stairs"))));
	public static final DeferredItem<Item> STONE_WINDMILL_WEAVE_STAIRS = ITEMS.register("stone_windmill_weave_stairs", () -> new BlockItem(BlockInit.STONE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("stone_windmill_weave_stairs"))));
	public static final DeferredItem<Item> MOSSY_STONE_WINDMILL_WEAVE_STAIRS = ITEMS.register("mossy_stone_windmill_weave_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_windmill_weave_stairs"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_WINDMILL_WEAVE_STAIRS = ITEMS.register("cobbled_deepslate_windmill_weave_stairs", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_windmill_weave_stairs"))));
	public static final DeferredItem<Item> DEEPSLATE_WINDMILL_WEAVE_STAIRS = ITEMS.register("deepslate_windmill_weave_stairs", () -> new BlockItem(BlockInit.DEEPSLATE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("deepslate_windmill_weave_stairs"))));
	public static final DeferredItem<Item> MUD_BRICK_WINDMILL_WEAVE_STAIRS = ITEMS.register("mud_brick_windmill_weave_stairs", () -> new BlockItem(BlockInit.MUD_BRICK_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("mud_brick_windmill_weave_stairs"))));
	public static final DeferredItem<Item> BLACKSTONE_WINDMILL_WEAVE_STAIRS = ITEMS.register("blackstone_windmill_weave_stairs", () -> new BlockItem(BlockInit.BLACKSTONE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("blackstone_windmill_weave_stairs"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_WINDMILL_WEAVE_STAIRS = ITEMS.register("dark_prismarine_windmill_weave_stairs", () -> new BlockItem(BlockInit.DARK_PRISMARINE_WINDMILL_WEAVE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_windmill_weave_stairs"))));

	public static final DeferredItem<Item> ANDESITE_FLAGSTONE_STAIRS = ITEMS.register("andesite_flagstone_stairs", () -> new BlockItem(BlockInit.ANDESITE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("andesite_flagstone_stairs"))));
	public static final DeferredItem<Item> DIORITE_FLAGSTONE_STAIRS = ITEMS.register("diorite_flagstone_stairs", () -> new BlockItem(BlockInit.DIORITE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("diorite_flagstone_stairs"))));
	public static final DeferredItem<Item> GRANITE_FLAGSTONE_STAIRS = ITEMS.register("granite_flagstone_stairs", () -> new BlockItem(BlockInit.GRANITE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("granite_flagstone_stairs"))));
	public static final DeferredItem<Item> SANDSTONE_FLAGSTONE_STAIRS = ITEMS.register("sandstone_flagstone_stairs", () -> new BlockItem(BlockInit.SANDSTONE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("sandstone_flagstone_stairs"))));
	public static final DeferredItem<Item> RED_SANDSTONE_FLAGSTONE_STAIRS = ITEMS.register("red_sandstone_flagstone_stairs", () -> new BlockItem(BlockInit.RED_SANDSTONE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_flagstone_stairs"))));
	public static final DeferredItem<Item> BRICK_FLAGSTONE_STAIRS = ITEMS.register("brick_flagstone_stairs", () -> new BlockItem(BlockInit.BRICK_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("brick_flagstone_stairs"))));
	public static final DeferredItem<Item> STONE_FLAGSTONE_STAIRS = ITEMS.register("stone_flagstone_stairs", () -> new BlockItem(BlockInit.STONE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("stone_flagstone_stairs"))));
	public static final DeferredItem<Item> MOSSY_STONE_FLAGSTONE_STAIRS = ITEMS.register("mossy_stone_flagstone_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_flagstone_stairs"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_FLAGSTONE_STAIRS = ITEMS.register("cobbled_deepslate_flagstone_stairs", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_flagstone_stairs"))));
	public static final DeferredItem<Item> DEEPSLATE_FLAGSTONE_STAIRS = ITEMS.register("deepslate_flagstone_stairs", () -> new BlockItem(BlockInit.DEEPSLATE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("deepslate_flagstone_stairs"))));
	public static final DeferredItem<Item> MUD_BRICK_FLAGSTONE_STAIRS = ITEMS.register("mud_brick_flagstone_stairs", () -> new BlockItem(BlockInit.MUD_BRICK_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("mud_brick_flagstone_stairs"))));
	public static final DeferredItem<Item> BLACKSTONE_FLAGSTONE_STAIRS = ITEMS.register("blackstone_flagstone_stairs", () -> new BlockItem(BlockInit.BLACKSTONE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("blackstone_flagstone_stairs"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_FLAGSTONE_STAIRS = ITEMS.register("dark_prismarine_flagstone_stairs", () -> new BlockItem(BlockInit.DARK_PRISMARINE_FLAGSTONE_STAIRS.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_flagstone_stairs"))));

	public static final DeferredItem<Item> ANDESITE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("andesite_crystal_floor_stairs", () -> new BlockItem(BlockInit.ANDESITE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("andesite_crystal_floor_stairs"))));
	public static final DeferredItem<Item> DIORITE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("diorite_crystal_floor_stairs", () -> new BlockItem(BlockInit.DIORITE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("diorite_crystal_floor_stairs"))));
	public static final DeferredItem<Item> GRANITE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("granite_crystal_floor_stairs", () -> new BlockItem(BlockInit.GRANITE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("granite_crystal_floor_stairs"))));
	public static final DeferredItem<Item> SANDSTONE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("sandstone_crystal_floor_stairs", () -> new BlockItem(BlockInit.SANDSTONE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("sandstone_crystal_floor_stairs"))));
	public static final DeferredItem<Item> RED_SANDSTONE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("red_sandstone_crystal_floor_stairs", () -> new BlockItem(BlockInit.RED_SANDSTONE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("red_sandstone_crystal_floor_stairs"))));
	public static final DeferredItem<Item> BRICK_CRYSTAL_FLOOR_STAIRS = ITEMS.register("brick_crystal_floor_stairs", () -> new BlockItem(BlockInit.BRICK_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("brick_crystal_floor_stairs"))));
	public static final DeferredItem<Item> STONE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("stone_crystal_floor_stairs", () -> new BlockItem(BlockInit.STONE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("stone_crystal_floor_stairs"))));
	public static final DeferredItem<Item> MOSSY_STONE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("mossy_stone_crystal_floor_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("mossy_stone_crystal_floor_stairs"))));
	public static final DeferredItem<Item> COBBLED_DEEPSLATE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("cobbled_deepslate_crystal_floor_stairs", () -> new BlockItem(BlockInit.COBBLED_DEEPSLATE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("cobbled_deepslate_crystal_floor_stairs"))));
	public static final DeferredItem<Item> DEEPSLATE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("deepslate_crystal_floor_stairs", () -> new BlockItem(BlockInit.DEEPSLATE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("deepslate_crystal_floor_stairs"))));
	public static final DeferredItem<Item> MUD_BRICK_CRYSTAL_FLOOR_STAIRS = ITEMS.register("mud_brick_crystal_floor_stairs", () -> new BlockItem(BlockInit.MUD_BRICK_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("mud_brick_crystal_floor_stairs"))));
	public static final DeferredItem<Item> BLACKSTONE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("blackstone_crystal_floor_stairs", () -> new BlockItem(BlockInit.BLACKSTONE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("blackstone_crystal_floor_stairs"))));
	public static final DeferredItem<Item> DARK_PRISMARINE_CRYSTAL_FLOOR_STAIRS = ITEMS.register("dark_prismarine_crystal_floor_stairs", () -> new BlockItem(BlockInit.DARK_PRISMARINE_CRYSTAL_FLOOR_STAIRS.get(), new Item.Properties().setId(getKeyForItem("dark_prismarine_crystal_floor_stairs"))));

	public static final DeferredItem<Item> PALE_OAK_PLANKS_PATH = ITEMS.register("pale_oak_planks_path", () -> new FuelItemBlock(BlockInit.PALE_OAK_PLANKS_PATH.get(), new Item.Properties().setId(getKeyForItem("pale_oak_planks_path"))));


}
